### ISSUE TITLE
Bug: Removes "showing results for x"

### ISSUE THREAD

**Issue by OtasGamer64** [PIjus-Github/TSMBRTRA-Remover#1]
It seems to work well, however, the problem is that it removes "showing results for x".
Can you fix that?

**Comment by Peeyos1** [comment]
I can't seem to fix that, unfortunately. I'll keep trying though.

**Comment by Peeyos1** [comment]
It seems that it's **unfixable**, unfortunately. I'll have to leave it that way, unless I somehow manage to find a workaround.
